helm:
  parameters:
  - name: containerSpec.image
    value: 742364958351.dkr.ecr.ap-south-1.amazonaws.com/oms-frontend
    forcestring: true
  - name: containerSpec.tag
    value: v1.0.15
    forcestring: true
