Labels:
  app: oms-frontend

deploymentSpec:
  replicaCout: 1

containerSpec:
  resources:
    requests:
      cpu: 250m
      memory: 1000Mi
    limits:
      cpu: 1000m
      memory: 1500Mi
  image: "742364958351.dkr.ecr.ap-south-1.amazonaws.com/oms-frontend"
  tag:  "v1.0.12"

serviceSpec:
  type: ClusterIP
  ports:
    - name: oms-frontend
      port: 3000
      targetport: 3000
      protocol: TCP