apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.Labels.app }}
  type: {{ .Values.serviceSpec.type }}
{{- range  .Values.serviceSpec.ports }}
  ports:
  - name: {{ .name }}
    protocol: {{ .protocol }}
    port: {{ .port }}
    targetPort: {{ .targetport }}
{{- end }}